server:
  port: 8080

spring:
  redis:
    host: 47.114.172.78
    database: 0
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
  cache:
    redis:
      time-to-live: -1
